INSERT INTO PUBLIC.USERS (EMAIL, NAME, PASSWORD)
VALUES ('user@mail.ru', 'user', 'user');

INSERT INTO PUBLIC.USERS (EMAIL, NAME, PASSWORD)
VALUES ('admin@mail.ru', 'admin', 'admin');

INSERT INTO PUBLIC.USER_ROLES (USER_ID, ROLE)
VALUES (1, 'USER');

INSERT INTO PUBLIC.USER_ROLES (USER_ID, ROLE)
VALUES (2, 'ADMIN');

INSERT INTO PUBLIC.RESTAURANTS (NAME)
VALUES ('rest1');

INSERT INTO PUBLIC.RESTAURANTS (NAME)
VALUES ('rest2');

INSERT INTO PUBLIC.MENUS (DATE, VOTES, RESTAURANT_ID)
VALUES ('2022-01-01', 10, 1);

INSERT INTO PUBLIC.MENUS (DATE, VOTES, RESTAURANT_ID)
VALUES ('2022-01-01', 8, 2);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (1, 'dish_rest1_1', 100.5);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (1, 'dish_rest1_2', 50);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (2, 'dish_rest2_1', 70.8);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (2, 'dish_rest2_2', 30.3);
