INSERT INTO PUBLIC.USERS (EMAIL, NAME, PASSWORD)
VALUES ('user1@mail.ru', 'user1', '{noop}user1');

INSERT INTO PUBLIC.USERS (EMAIL, NAME, PASSWORD)
VALUES ('user2@mail.ru', 'user2', '{noop}user2');

INSERT INTO PUBLIC.USERS (EMAIL, NAME, PASSWORD)
VALUES ('admin@mail.ru', 'admin', '{noop}admin');

INSERT INTO PUBLIC.USER_ROLES (USER_ID, ROLE)
VALUES (1, 'USER');

INSERT INTO PUBLIC.USER_ROLES (USER_ID, ROLE)
VALUES (2, 'USER');

INSERT INTO PUBLIC.USER_ROLES (USER_ID, ROLE)
VALUES (3, 'ADMIN');

INSERT INTO PUBLIC.RESTAURANTS (NAME)
VALUES ('rest1');

INSERT INTO PUBLIC.RESTAURANTS (NAME)
VALUES ('rest2');

INSERT INTO PUBLIC.MENUS (MENU_DATE, RESTAURANT_ID)
VALUES (now() - 1, 1);

INSERT INTO PUBLIC.MENUS (MENU_DATE, RESTAURANT_ID)
VALUES (now() - 1, 2);

INSERT INTO PUBLIC.MENUS (MENU_DATE, RESTAURANT_ID)
VALUES (now(), 1);

INSERT INTO PUBLIC.MENUS (MENU_DATE, RESTAURANT_ID)
VALUES (now(), 2);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (1, 'dish_rest1_1_1', 100);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (1, 'dish_rest1_1_2', 50);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (2, 'dish_rest2_1_1', 70);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (2, 'dish_rest2_1_2', 30);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (3, 'dish_rest1_2_1', 150);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (3, 'dish_rest1_2_2', 75);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (4, 'dish_rest2_2_1', 90);

INSERT INTO PUBLIC.MENU_DISHES (MENU_ID, NAME, PRICE)
VALUES (4, 'dish_rest2_2_2', 132);

INSERT INTO PUBLIC.VOTES (VOTING_DATE, RESTAURANT_ID, USER_ID)
VALUES (now()-1, 1, 1);

INSERT INTO PUBLIC.VOTES (VOTING_DATE, RESTAURANT_ID, USER_ID)
VALUES (now()-1, 2, 2);

INSERT INTO PUBLIC.VOTES (VOTING_DATE, RESTAURANT_ID, USER_ID)
VALUES (now(), 2, 1);